add_newline = false

format="$all"

[character]
success_symbol = '[<I>](bold fg:246) [➜](bold green)'
cancel_symbol = '[<I>](bold fg:246) [➜](bold yellow)'
error_symbol = '[<I>](bold fg:246) [➜](bold red)'
vicmd_symbol = '[<N>](bold fg:246) [➜](bold green)' # Backwards compatibility with not my patch
vicmd_success_symbol = '[<N>](bold fg:246) [➜](bold green)'
vicmd_cancel_symbol = '[<N>](bold fg:246) [➜](bold yellow)'
vicmd_error_symbol = '[<N>](bold fg:246) [➜](bold red)'

[aws]
disabled = true

[battery]
disabled = true

[cmd_duration]
min_time = 5_000
show_milliseconds = true

[directory]
truncation_length = 8
truncate_to_repo = true
read_only_symbol= ' '

[hostname]
ssh_only = false

[username]
show_always = true
format = "[$user]($style)@"

[package]
disabled = true

[python]
scan_for_pyfiles = false

[cmake]
symbol ="🛆 "
